---
title: "JHU CSSE COVID-19 Dataset analysis"
author: "cloud-erik"
date: "21 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Import

First importing the COVID-19 Dataset as CSV file from JHU Github <https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data> and create a summary

```{r import_data, echo=TRUE}
url_confirmed <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
url_death <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
url_recovered <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

#check.names has to be FALSE because otherwise "/" will be replaced in Header names
covid_confirmed <- read.csv(url_confirmed, header = TRUE, check.names = FALSE)
covid_death <- read.csv(url_death, header = TRUE, check.names = FALSE)
covid_recovered <- read.csv(url_recovered, header = TRUE, check.names = FALSE)
summary(covid_confirmed)
summary(covid_death)
summary(covid_recovered)
```

Clean the date and join in into one table. "transpose" with pivot_loger the dates into rows, drop the lat and long columns, make date a date format, country a valid name and drop the Province by sum it by country.

```{r cleaning, echo=TRUE}
library(tidyverse)
library(lubridate)

covid_confirmed <- covid_confirmed %>%
  pivot_longer(cols = -c("Province/State", "Country/Region", "Lat", "Long"),
               names_to = "date", values_to = "confirmed") %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long)) %>%
  rename(Country = "Country/Region") %>%
  group_by(Country, date) %>% summarise(confirmed = sum(confirmed))

covid_death <- covid_death %>%
  pivot_longer(cols = -c("Province/State", "Country/Region", "Lat", "Long"),
               names_to = "date", values_to = "death") %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long)) %>%
  rename(Country = "Country/Region") %>%
  group_by(Country, date) %>% summarise(death = sum(death))

covid_recovered <- covid_recovered %>%
  pivot_longer(cols = -c("Province/State", "Country/Region", "Lat", "Long"),
               names_to = "date", values_to = "recovered") %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat, Long)) %>%
  rename(Country = "Country/Region") %>%
  group_by(Country, date) %>% summarise(recovered = sum(recovered))

# Join together in covid_data
covid_data <- merge.data.frame(covid_confirmed, covid_death)
covid_data <- merge.data.frame(covid_data, covid_recovered)

summary(covid_data)

```

First plot a timeline
```{r timeline, echo=TRUE}
library(timetk)

p <- ggplot(covid_data, aes(x = date)) +
  geom_line(color="darkorchid4", size=1, alpha=0.5, linetype=1, aes(y = confirmed)) +
#  geom_line(size=1, alpha=0.5, linetype=1, aes(y = confirmed, color=Country)) +
  geom_line(color="yellow", size=1, alpha=0.5, linetype=1, aes(y = recovered)) +
  geom_line(color="blue", size=1, alpha=0.5, linetype=1, aes(y = death)) +
#geom_point(color="darkorchid4") +
  labs(x="Date") +
  ggtitle("Covid-19 over time")
p
```


```{r esssionifo, echo=TRUE}
sessionInfo()
```
